{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmapaas.fullname" . }}-api
  labels:
    {{- include "nmapaas.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "auth.apiKey is required" .Values.auth.apiKey | quote }}
{{- end }}
{{- if not .Values.pia.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmapaas.fullname" . }}-pia
  labels:
    {{- include "nmapaas.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "pia.username is required" .Values.pia.username | quote }}
  password: {{ required "pia.password is required" .Values.pia.password | quote }}
{{- end }}
