{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmapaas.fullname" . }}-api
  labels:
    {{- include "nmapaas.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "auth.apiKey is required" .Values.auth.apiKey | quote }}
{{- end }}
{{- if .Values.vpn.configs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nmapaas.fullname" . }}-vpn
  labels:
    {{- include "nmapaas.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $config := .Values.vpn.configs }}
  {{ $name }}.conf: |
    {{- $config | nindent 4 }}
  {{- end }}
{{- end }}
